### ISSUE TITLE
Expectations

### ISSUE THREAD

**Issue by avinashsai** [facebookresearch/optimizers#1]
Hi,

I am curious about the contributions we can make to this repo. This repo is for the optimizers that are not included in the official pytorch library?

Thanks.

**Comment by hjmshi** [comment]
Thanks for your interest in the repo! This repo's focus is to provide an opportunity for external collaboration and development of optimizers that are not included (yet) in the official PyTorch library. Please feel free to propose improvements to the optimizers supported in this repo. However, it is probably not appropriate to PR a completely new optimizer - you are better off creating a separate public repo for that development. I will update the CONTRIBUTING file to clarify this. Please let me know if this answers your questions.

**Comment by rish-16** [comment]
Are there any examples of optimisers not part of the standard PyTorch library? I'd love to get started if there's an existing to-do list of options.

**Comment by hjmshi** [comment]
Hi Rishabh, all optimizers (so far) are not part of the standard PyTorch library. There may be more to come!

Closing this issue now since the CONTRIBUTING file has been changed.
