### ISSUE TITLE
pip install-able

### ISSUE THREAD

**Issue by windsornguyen** [facebookresearch/optimizers#16]
hello,

i was wondering if the team has any intention to make distributed shampoo more accessible e.g. making it available pip install-able via pypi

thanks

**Comment by hjmshi** [comment]
Hi @windsornguyen, since we are still continuing to develop the PyTorch Distributed Shampoo code, we haven't chosen to make it more accessible via PyPI. 

Is there a reason why you're looking for the PyTorch Distributed Shampoo code to be PyPI installable? Thanks!

**Comment by windsornguyen** [comment]
@hjmshi thank you for the response! no worries, i was looking to include shampoo in a paper implementation and it's just one less step for users to worry about if they can just quickly pip install all the dependencies

**Comment by hjmshi** [comment]
Hi @windsornguyen, FYI, @tsunghsienlee is looking into this. We may add support for this later. Thanks again for your interest!
