### ISSUE TITLE
Are eigh calls spread across gpus? or all on a single gpu?

### ISSUE THREAD

**Issue by nikhilvyas** [facebookresearch/optimizers#17]
I did not find any documentation relating to this in the code or the paper.

**Comment by hjmshi** [comment]
Yes, the `eigh` calls are spread across GPUs. In our v2 implementation, all of the computation and optimizer states associated with each parameter block is distributed. Only the final parameter update is replicated across all devices (in the DDP setup). Let me know if you have any other questions!
