### ISSUE TITLE
Typo in Algorithm 2 in the Distributed Shampoo paper: beta1 used instead of beta2

### ISSUE THREAD

**Issue by jondeuce** [facebookresearch/optimizers#21]
Algorithm 2 in [the distributed shampoo paper](https://arxiv.org/pdf/2309.06497) uses `beta1` in the EMA accumulations for `L_t` and `R_t`:

![Screenshot from 2024-09-13 16-08-30](https://github.com/user-attachments/assets/2db610fd-d56d-4814-ada2-c714dbec1562)

The paper text, as well as equations 25-26 indicate that `beta2` should be used:

![Screenshot from 2024-09-13 16-15-20](https://github.com/user-attachments/assets/6c09f76c-c8bf-4154-9589-bb042954d896)

Quick glance at the code and it seems like `beta2` is used, as expected.

**Comment by hjmshi** [comment]
Thanks @jondeuce! We will have to fix this in our revision. :)
