### ISSUE TITLE
resuming shampoo from checkpoint results in preconditioners with tensors on wrong device

### ISSUE THREAD

**Issue by rwightman** [facebookresearch/optimizers#3]
On loading a state dict from checkpoint, shampoo doesn't appear to be setup to handle devices properly. The preconditioners end up with tensors on the CPU after loading the state dict.

**Comment by hjmshi** [comment]
Thanks for your interest, Ross, and giving the implementation a try. Can you provide some more background on your particular workload and how you are configuring Shampoo and implementing checkpointing? We ran some simple tests on our side and checkpointing appears to work, but maybe there's something we aren't capturing through our crude testing. Thanks!

**Comment by rwightman** [comment]
@hjmshi yes, exactly that, was going to respond this afternoon, but I use the mapping and without overriding the state dict load it's hard to remap the tensors that are held in the precond classes to the proper device...

**Comment by hjmshi** [comment]
Hi Ross, we have updated the Shampoo implementation to overwrite load_state_dict as described above. Can you check if it works for you now? Thanks!

**Comment by hjmshi** [comment]
Closing this if there are no other comments.
